---
- name: download go archive...
  get_url: url={{go_tgz_url}} dest=/tmp/{{go_tgz}}

- name: mkdir target
  file: >-
    path=/opt/{{go_name}}
    owner=root
    group=root
    mode=0755
    state=directory
    
- name: unarchive go...
  unarchive: copy=no src=/tmp/{{go_tgz}} dest=/opt/{{go_name}}

- name: link /opt/go
  file: >-
    src=/opt/{{go_name}}
    dest=/opt/go
    state=link
  
- name: set go environment variables
  copy: >
    src=go.sh
    dest=/etc/profile.d/go.sh
    mode=0644
    owner=root
    group=root
