---
- name: download go archive...
  become: yes
  become_user: root
  get_url: >
    url={{go_tgz_url}}
    dest=/tmp/{{go_tgz}}
    mode=0644

- name: unarchive go...
  become: yes
  become_user: root
  unarchive: >
    copy=no
    src=/tmp/{{go_tgz}}
    dest=/usr/local
    creates=/usr/local/go/bin/go

- name: set go environment variables
  become: yes
  become_user: root
  template: >
    src=go.sh.j2
    dest=/etc/profile.d/go.sh
    mode=0644
