---
- name: installing golang packages...
  become_user: root
  become: '{{go_privilege_escalation}}'
  with_items: '{{go_pkg_list |default([])}}'
  register: go_installed
  package:
    name: '{{item}}'
    state: present

- name: set environment variables
  when: go_installed | changed
  blockinfile:
    dest: ~/.bash_profile
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK golang environment variables"
    block: |
      {{ go_env_block }}