---
- name: download go archive...
  become: '{{go_privilege_escalation}}'
  become_user: root
  get_url: >
    url={{go_tgz_url}}
    dest=/tmp/{{go_tgz}}
    mode=0644

- name: create go version directory
  become: '{{go_privilege_escalation}}'
  become_user: root
  file: >-
    path={{go_dir}}
    state=directory
    mode=0755
    
- name: unarchive go...
  become: '{{go_privilege_escalation}}'
  become_user: root
  unarchive: >
    copy=no
    src=/tmp/{{go_tgz}}
    dest={{go_dir}}
    creates={{go_dir}}/go

- name: link in latest go
  become: '{{go_privilege_escalation}}'
  become_user: root
  file: >-
    src={{go_dir}}/go
    dest={{go_parent_dir}}/go
    state=link

- name: extra dirs
  become: '{{go_privilege_escalation}}'
  become_user: root
  with_items: '{{go_extra_dirs|default([])}}'
  file: >-
    path={{item}}
    state=directory
    mode=0755

- name: extra links
  become: '{{go_privilege_escalation}}'
  become_user: root
  with_items: '{{go_extra_links|default([])}}'
  file: >-
    src={{item.src}}
    dest={{item.dest}}
    state=link

