---
- name: download go archive...
  become: yes
  become_user: root
  get_url: >
    url={{go_tgz_url}}
    dest=/tmp/{{go_tgz}}
    mode=0644

- name: create go version directory
  become: yes
  become_user: root
  file: >-
    path={{go_dir}}
    state=directory
    mode=0755
    
- name: unarchive go...
  become: yes
  become_user: root
  unarchive: >
    copy=no
    src=/tmp/{{go_tgz}}
    dest={{go_dir}}
    creates={{go_dir}}/go

- name: link in latest go
  become: yes
  become_user: root
  file: >-
    src={{go_dir}}/go
    dest={{go_parent_dir}}/go
    state=link

- name: install godep
  become: yes
  become_user: root
  environment:
    GOROOT: '{{go_root}}'
    GOPATH: '{{go_path}}'
    PATH: '{{go_root}}/bin:{{go_path}}/bin'
  command: /usr/local/go/bin/go get github.com/tools/godep
  args:
    creates: '{{go_path}}/src/github.com/tools/godep'

- name: set go environment variables
  become: yes
  become_user: root
  with_items:
    - go.sh
  template: >
    src={{item}}.j2
    dest={{go_profile_dir}}/{{item}}
    mode=0644

